# Regenerates docs/undocumented.md: a checklist of exported symbols that lack a
# docstring. Run from the repo root with the docs environment:
#
#     julia --project=docs docs/undocumented.jl
#
# A symbol counts as documented iff its binding appears in some module's
# `Base.Docs.meta` dict (i.e. a `"""docstring"""` was attached to it). Module
# docstrings and per-field struct docs are not tracked.

using Bifrost

documented_vars(m::Module) = Set(b.var for b in keys(Base.Docs.meta(m)))

const MODS = [
    (Bifrost.MaterialProperties, "api/material-properties.md"),
    (Bifrost.PathGeometry,       "api/path-geometry.md"),
    (Bifrost.FiberCS,            "api/fiber-cross-section.md"),
    (Bifrost.FiberPath,          "api/fiber-path.md"),
    (Bifrost.PathIntegral,       "api/path-integral.md"),
    (Bifrost.Plots,              "api/plots.md"),
]

const OUT = joinpath(@__DIR__, "undocumented.md")

open(OUT, "w") do io
    println(io, "# Undocumented exported symbols")
    println(io)
    println(io, "Auto-generated by `docs/undocumented.jl`. Checklist of **exported** symbols")
    println(io, "that currently lack a `\"\"\"docstring\"\"\"`. The Documenter `@autodocs` blocks")
    println(io, "render only documented symbols, so each entry below is a gap on the")
    println(io, "corresponding API page. This file is a worklist; it is intentionally **not**")
    println(io, "wired into the site navigation.")
    println(io)
    println(io, "Module docstrings and per-field struct docs are not tracked here — only")
    println(io, "top-level exported bindings.")
    println(io)
    grand_total = 0
    grand_undoc = 0
    summaries = String[]
    bodies = String[]
    for (m, page) in MODS
        doc = documented_vars(m)
        undoc = Symbol[]
        for n in names(m)
            n === nameof(m) && continue
            n in doc && continue
            push!(undoc, n)
        end
        sort!(undoc, by = String)
        total = length(names(m)) - 1
        ndoc = total - length(undoc)
        grand_total += total
        grand_undoc += length(undoc)
        push!(summaries,
              "| `$(nameof(m))` | $ndoc | $(length(undoc)) | $total | [$page]($page) |")
        b = IOBuffer()
        println(b, "## `$(nameof(m))`")
        println(b)
        println(b, "$ndoc of $total exported symbols documented; ",
                   "$(length(undoc)) remaining.")
        println(b)
        if isempty(undoc)
            println(b, "_All exported symbols documented._")
        else
            for n in undoc
                println(b, "- [ ] `$n`")
            end
        end
        println(b)
        push!(bodies, String(take!(b)))
    end
    println(io, "## Summary")
    println(io)
    println(io, "| Module | Documented | Undocumented | Exported | API page |")
    println(io, "| --- | ---: | ---: | ---: | --- |")
    for s in summaries
        println(io, s)
    end
    gdoc = grand_total - grand_undoc
    println(io, "| **Total** | **$gdoc** | **$grand_undoc** | **$grand_total** | |")
    println(io)
    for body in bodies
        print(io, body)
    end
end
println("wrote ", OUT)
